print("Interactive Text Game")
print("By: Harshith Gudur\n")
name = input("What is your name? :  ")
print("Hello, " + name + ". I am Billy the Bot!\n" + "( ^◡^)\n")
question = input("Do you want to learn about PTSD today?  : ")

if question == "yes":
    print("Great! Let's Continue.")
else:
    print("That was rude!")
    print("PTSD is a very dangerous mental health problem that many people suffer from!")
    print("It is important to learn about such problems so that you can help someone who suffers from it\n" + "Or you can understand more so you can help yourself")
print("In a short sentence explain what you think PTSD is...\n" + "We can compare this to the response you will be asked after completing this lesson")
first_entry = input("ENTRY  : ")
print("Great, Let's get started!")
blank = input("CLICK ENTER TO CONTINUE")
print("PTSD stands for Post-Traumatic Stress Disorder")
blank = input("CLICK ENTER TO CONTINUE")
print("PTSD often occurs when someone experiences something very terryfiying or scary. \n" + "( ゜o゜)")
blank = input("CLICK ENTER TO CONTINUE")
print("SYMPTOMS\n")
print("-Unbarable Nightmares\n" + "-Horrifiying Flashbacks\n" + "-Terryfiying Episodes\n" + "-Severe Anxiety\n")
print("People often don't see the symptoms until months or even years.\n" + "PTSD gets worse you get more stressed; It can impact your everyday activities.\n")
print("Many people with PTSD get easily startled, are always on guard, have trouble sleeping and concentrating, and many other things along those lines.\n")
print("(;╹⌓╹)")
blank = input("CLICK ENTER TO CONTINUE")
print("Now this might sound scary...\n" + "But many people recover from PTSD and it's is important to help people with PTSD to recover!\n")
print("If you really want to help someone with PTSD\n" + "The best thing you can do is help them find a counselor who has experience dealing with PTSD\n")
print("( ⌒o⌒)人(⌒-⌒ )\n")
blank = input("CLICK ENTER TO CONTINUE")
print("Now, Type down what you know about PTSD.")
second_entry = input("ENTRY  : ")
print("Here is your first entry : \n" + first_entry + "\n")
print("Did you learn anything new?\n\n")
print("Thank You Very Much for taking part in raising awareness towards people with PTSD!\n")
print("Share The Link to this GitHub page any small difference you make can impact a lot of people!\n")
print("────────╠███████───███████╠─────────────")
print("───────╠█████████─╠█████████────────────")
print("───────█████████████████████╠───────────")
print("──────╠██████████████████████───────────")
print("──────███████████████████████───────────")
print("──────███████████████████████╠──────────")
print("──────███████████████████████╠──────────")
print("──────███████████████████████───────────")
print("──────╠██████████████████████───────────")
print("──────╠█████████████████████╠───────────")
print("───────█████████████████████────────────")
print("───────╠███████████████████╠────────────")
print("────────╠███████████──╠████─────────────")
print("─────────██████████─────╠█╠─────────────")
print("─────────╠████████──███─────────────────")
print("──────────╠███████─╠█████───────────────")
print("─────╠╠────╠██████─╠███████─────────────")
print("──█████╠────╠█████╠─╠███████╠───────────")
print("─╠███████╠█╠─╠█████╠──████████╠─────────")
print("╠███████████╠──█████───╠████████╠───────")
print("╠█████████████──╠██╠─────╠████████╠─────")
print("─██████████████───────────█████████╠────")
print("──╠█████████████╠───────╠███████████╠───")
print("───╠█████████████████████████████████╠──")
print("────╠█████████████████████████████████──")
print("─────╠█████████████████████████████████─")
print("───────████████████████████████████████╠")
print("────────╠███████████████████████████████")
print("─────────╠██████████████████████████████")
print("───────────█████████████████████████████")
print("────────────╠██████████████████████████─")
print("───────────────────────────────╠██████──")
print("─────────────────────────────────███╠───")
print("─────────────────────────────────╠█╠────")






